// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

// GetPokemonByID provides a mock function with given fields: w, r
func (_m *ControllerInterface) GetPokemonByID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetPokemonByName provides a mock function with given fields: w, r
func (_m *ControllerInterface) GetPokemonByName(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// PostPokemon provides a mock function with given fields: w, r
func (_m *ControllerInterface) PostPokemon(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
