// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/rayl17/academy-go-q42021/model"
	mock "github.com/stretchr/testify/mock"
)

// Usecaseinterface is an autogenerated mock type for the Usecaseinterface type
type Usecaseinterface struct {
	mock.Mock
}

// GetPokemonByID provides a mock function with given fields: id
func (_m *Usecaseinterface) GetPokemonByID(id string) (*model.Pokemon, error) {
	ret := _m.Called(id)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(string) *model.Pokemon); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPokemonByName provides a mock function with given fields: name
func (_m *Usecaseinterface) GetPokemonByName(name string) (*model.Pokemon, error) {
	ret := _m.Called(name)

	var r0 *model.Pokemon
	if rf, ok := ret.Get(0).(func(string) *model.Pokemon); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pokemon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SavePokemonByNameAPI provides a mock function with given fields: name
func (_m *Usecaseinterface) SavePokemonByNameAPI(name string) (string, error) {
	ret := _m.Called(name)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
